
# Re-build the main config file for leftwm.
build-leftwm-config:
   expandr expand -o tmp_config.ron leftwm_main.exr \
   && leftwm check tmp_config.ron


# Re-build the main config file for leftwm and replace the active config
# WARNING: This will overwrite ../config.ron
replace-config:
   expandr expand -o ../config.ron leftwm_main.exr \
   && leftwm check

reload: replace-config
   leftwm command SoftReload

